### ISSUE TITLE
pip package urllib3 fails to build for integration-tests container

### ISSUE THREAD

**Issue by chrinorse** [gardenlinux/gardenlinux#775]
**What happened**:
ontainer build fails with
```
STEP 8/9: RUN cd /_pipfiles && pipenv --python 3.9 install --system --dev && cd / && rm -rf /_pipfiles
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pipenv/vendor/requests/packages/__init__.py", line 27, in <module>
    from . import urllib3
  File "/usr/local/lib/python3.10/dist-packages/pipenv/vendor/requests/packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/local/lib/python3.10/dist-packages/pipenv/vendor/requests/packages/urllib3/connectionpool.py", line 35, in <module>
    from .connection import (
  File "/usr/local/lib/python3.10/dist-packages/pipenv/vendor/requests/packages/urllib3/connection.py", line 54, in <module>
    from ._collections import HTTPHeaderDict
  File "/usr/local/lib/python3.10/dist-packages/pipenv/vendor/requests/packages/urllib3/_collections.py", line 2, in <module>
    from collections import Mapping, MutableMapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

**Comment by nanory** [comment]
Hi @chrinorse,

I think I found the reason. It seems that `debian/testing` has switched from Python 3.9 to 3.10. However, the pipenv version that we are using is quiet outdated and doesn't seems to work with Python3.10.

Maybe that's the reason why they have removed pipenv from `debian/testing` as mentioned [here](https://tracker.debian.org/news/1318536/pipenv-removed-from-testing/)

Once you use a newer pipenv version like `2022.4.8` (via pip) and you enforce Python 3.10, the installation via of the Pipfile modules seems to work again.

We need to adjust these two parameters as far as I can see:
* https://github.com/gardenlinux/gardenlinux/blob/use-pytest-in-build-sh/container/base-test/Dockerfile#L35
* https://github.com/gardenlinux/gardenlinux/blob/use-pytest-in-build-sh/tests/Pipfile.lock#L8
